spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 300_000
      connection-timeout: 30_000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 180_000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    locations:
      - classpath:db/migration
  redis:
    database: 0
    timeout: 10000
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5

server:
  tomcat:
    uri-encoding: UTF-8

beetlsql:
  sqlManagers: coreSqlManager
  coreSqlManager:
    ds: dataSource
    dev: true
    basePackage: com.example.**.mapper
    daoSuffix: Mapper
    sqlPath: mdsql
    nameConversion: org.beetl.sql.core.UnderlinedNameConversion
    dbStyle: org.beetl.sql.core.db.MySqlStyle
    sqlFileCharset: utf-8


erupt-app:
  verifyCodeCount: 2
  pwdTransferEncrypt: true
  locales: [ "zh-CN","en-US"]

erupt:
  csrfInspect: false
  redisSession: true
  uploadPath: D:/erupt/pictures
  keepUploadFileName: false
  upms:
    expireTimeByLogin: 60
    strictRoleMenuLegal: true
  job.enable: true
  security.recordOperateLog: true

magic-api:
  web: /magic/web
  resource:
    type: database
    tableName: magic_api_file
    readonly: false
  prefix: /magic-api
  auto-import-module: db
  auto-import-package: java.lang.*,java.util.*
  allow-override: false
  sql-column-case: camel
  # editor-config: classpath:./magic-editor.js
  support-cross-domain: true
  secret-key: 123456
  push-path: /_magic-api-sync
  show-sql: true
  compile-cache-size: 500
  persistence-response-body: true
  date-pattern:
    - yyyy-MM-dd
    - yyyy-MM-dd HH:mm:ss
    - yyyyMMddHHmmss
    - yyyyMMdd
  response: |-
    {
      code,
      message: msg,
      data
    }
  response-code:
    success: 1
    invalid: 0
    exception: -1
  banner: false
  thread-pool-executor-size: 8
  throw-exception: false
  crud:
    logic-delete-column: deleted
    logic-delete-value: 1
  cache:
    capacity: 10000
    ttl: -1
    enable: true
  page:
    size: pageSize
    page: pageNum
    default-page: 1
    default-size: 10
  backup:
    enable: true
    max-history: -1
    table-name: magic_api_backup
  security:
    username: admin
    password: 123456
#  swagger:
#    version: 1.0
#    description: MagicAPI 接口信息
#    title: MagicAPI Swagger Docs
#    name: MagicAPI 接口
#    location: /v2/api-docs/magic-api/swagger2.json
  debug:
    timeout: 60