spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo2?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    database: 2
    timeout: 10000
    host: 127.0.0.1
    port: 6379
    password: 123456
  jpa:
    generate-ddl: false

erupt:
  uploadPath: /opt/erupt/pictures

magic-api:
  resource:
    readonly: true
  secret-key: 123456
  push-path: /_magic-api-sync
  security:
    username: admin
    password: 123456
  backup:
    enable: true
    max-history: -1
    table-name: magic_api_backup